# Site settings
title: How to exit Vi?
author: Saša Stamenković
description: The ultimate quit Vi resource

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-6935870-11
google_tag_manager:

# Build settings
markdown: kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: pretty
sass:
  style: compressed
gems:
  - jekyll-sitemap

# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
